# Configura aquí tus secretos para Streamlit (localmente)
# No subas tu clave real a un repositorio público.
# En Streamlit Cloud, configura los secretos desde la UI: App -> Settings -> Secrets

OPENAI_API_KEY = "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"
